branches:
  only:
  - master

language: c

compiler: gcc

matrix:
  include:
    - os: linux
      dist: xenial
    - os: windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install build-essential ; fi
script: 
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; make ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; ./main.exe ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; gcc main.c MNIST_API.h MNIST_API_impl.c -o main ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; main.exe ; fi